#!/bin/sh
test -z "$DISPLAY" && DISPLAY=:0
config="$HOME/.onscreen"
host=$(test -n "$1" && echo "$1" || { test -f $config && cat $config 2>/dev/null; })
res=$(LANG=C xrandr | grep connect | head -n 1 | grep -o '[0-9]\+x[0-9]\+')
imag="/onscreen.$$.jpg"
scrot "$HOME/$imag"
cat "$HOME/$imag" | ssh $host "
	cat - > \$HOME/$imag
	DISPLAY=:0 feh -ZF \$HOME/$imag & sleep 10
	rm \$HOME/$imag; killall feh"
rm "$HOME/$imag"